package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
)

func main() {
	data, err := os.ReadFile("api/openapi.json")
	if err != nil {
		panic(err)
	}
	var doc struct {
		Paths map[string]any `json:"paths"`
	}
	if err := json.Unmarshal(data, &doc); err != nil {
		panic(err)
	}
	paths := make([]string, 0, len(doc.Paths))
	for path := range doc.Paths {
		paths = append(paths, path)
	}
	sort.Strings(paths)

	var buf bytes.Buffer
	buf.WriteString("// Code generated by go run ./internal/cmd/apicmd/genpaths; DO NOT EDIT.\n")
	buf.WriteString("package apicmd\n\n")
	buf.WriteString("var generatedAPIPaths = []string{\n")
	for _, path := range paths {
		fmt.Fprintf(&buf, "\t%q,\n", path)
	}
	buf.WriteString("}\n")

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("internal/cmd/apicmd/api_paths_gen.go", formatted, 0o644); err != nil {
		panic(err)
	}
}
